<a href="https://colab.research.google.com/github/team7-7jeonpalgi/PetViz/blob/seung-oh/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded1 = files.upload()
uploaded2 = files.upload()
uploaded3 = files.upload()
uploaded4 = files.upload()
uploaded5 = files.upload()

Saving 입양대상 동물_20250516.csv to 입양대상 동물_20250516 (1).csv

Saving 영업장목록_20250516.csv to 영업장목록_20250516.csv

Saving 반환대상 동물공고_20250516.csv to 반환대상 동물공고_20250516.csv

Saving 동물보호센터 목록_20250516.csv to 동물보호센터 목록_20250516.csv

Saving 동물병원 목록_20250516.csv to 동물병원 목록_20250516.csv

In [ ]:
import pandas as pd

df1 = pd.read_csv('입양대상 동물_20250516.csv')
df3 = pd.read_csv('반환대상 동물공고_20250516.csv')
df4 = pd.read_csv('동물보호센터 목록_20250516.csv')
df5 = pd.read_csv('동물병원 목록_20250516.csv')

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13038 entries, 0 to 13037
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   공고번호     13038 non-null  object
 1   동물등록번호   731 non-null    object
 2   품종       13038 non-null  object
 3   색상       3813 non-null   object
 4   성별       13038 non-null  object
 5   중성화      10174 non-null  object
 6   나이/체중    13038 non-null  object
 7   구조시 특징   13037 non-null  object
 8   특징(사회성)  239 non-null    object
 9   특징(건강)   229 non-null    object
 10  발생장소     13038 non-null  object
 11  접수일시     13038 non-null  object
 12  기타사항     0 non-null      float64
 13  관할기관     13038 non-null  object
 14  상태       13038 non-null  object
 15  보호센터     13038 non-null  object
 16  보호센터연락처  13038 non-null  object
 17  보호장소     13038 non-null  object
dtypes: float64(1), object(17)
memory usage: 1.8+ MB

In [ ]:
df1.drop(['동물등록번호','구조시 특징','특징(사회성)','특징(건강)', '색상'], axis=1, inplace=True)

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13038 entries, 0 to 13037
Data columns (total 12 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   공고번호     13038 non-null  object
 1   품종       13038 non-null  object
 2   성별       13038 non-null  object
 3   중성화      10174 non-null  object
 4   나이/체중    13038 non-null  object
 5   발생장소     13038 non-null  object
 6   접수일시     13038 non-null  object
 7   관할기관     13038 non-null  object
 8   상태       13038 non-null  object
 9   보호센터     13038 non-null  object
 10  보호센터연락처  13038 non-null  object
 11  보호장소     13038 non-null  object
dtypes: object(12)
memory usage: 1.2+ MB

In [ ]:
df1['성별'].value_counts(dropna=False)

성별
암컷    6694
수컷    5933
미상     411
Name: count, dtype: int64

In [ ]:
df1['성별'] = df1['성별'].replace({'암컷':"여", "수컷":"남"})

In [ ]:
gender_counts = df1['성별'].value_counts()
print(gender_counts)

성별
여     6694
남     5933
미상     411
Name: count, dtype: int64

In [ ]:
df1['종'] = df1['품종'].str.extract(r'\[(개|고양이)\]')

In [ ]:
df1['종'] = df1['종'].fillna('기타')

In [ ]:
species_counts = df1['종'].value_counts()
print(species_counts)

종
개      11526
고양이     1401
기타       111
Name: count, dtype: int64

In [ ]:
df1['시도'] = df1['관할기관'].str.split().str[0]
df1['시도'] = df1['시도'].fillna('기타지역')
region_counts = df1['시도'].value_counts()

In [ ]:
print(region_counts)

시도
전북특별자치도    1799
경기도        1673
경상남도       1555
전라남도       1382
경상북도       1325
충청남도       1229
강원특별자치도    1064
부산광역시       548
충청북도        523
울산광역시       406
인천광역시       352
광주광역시       292
대구광역시       240
서울특별시       237
대전광역시       195
제주특별자치도     155
세종특별자치시      63
Name: count, dtype: int64

In [ ]:
df1['중성화'].value_counts(dropna=False)

중성화
아니오    9359
NaN    2864
예       815
Name: count, dtype: int64

In [ ]:
df1['중성화']=df1['중성화'].fillna('미확인')

In [ ]:
df1['중성화'] = df1['중성화'].replace({'예':'o', '아니오':'x'})

In [ ]:
neuter_counts = df1['중성화'].value_counts()
print(neuter_counts)

중성화
x      9359
미확인    2864
o       815
Name: count, dtype: int64

In [ ]:
df1.drop(["상태", '발생장소','나이/체중','공고번호','보호센터연락처'], axis=1, inplace=True)

KeyError: "['상태', '발생장소', '나이/체중', '공고번호', '보호센터연락처'] not found in axis"

In [ ]:
df1.drop(["보호장소"], axis=1, inplace=True)

In [ ]:
df1.to_csv('정제된 입양대상 동물_20250516.csv', index=False, encoding='utf-8-sig')
files.download('정제된 입양대상 동물_20250516.csv')

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1961 entries, 0 to 1960
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   번호       1961 non-null   int64
 1   구분       1961 non-null   object
 2   업체명      1961 non-null   object
 3   전화번호     1895 non-null   object
 4   소재지      1922 non-null   object
 5   인허가 정보   1961 non-null   int64
 6   이전인허가정보  0 non-null      float64
 7   생산축종     1763 non-null   object
 8   비고       1961 non-null   object
dtypes: float64(1), int64(2), object(6)
memory usage: 138.0+ KB

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1350 entries, 0 to 1349
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   공고번호      1350 non-null   object
 1   동물등록번호    38 non-null     float64
 2   동물종류      1350 non-null   object
 3   품종        1350 non-null   object
 4   털색        0 non-null      float64
 5   성별        1350 non-null   object
 6   중성화 여부    1350 non-null   object
 7   특징        1350 non-null   object
 8   구조일       1350 non-null   object
 9   구조사유      351 non-null    object
 10  구조장소      1350 non-null   object
 11  공고기간      1350 non-null   object
 12  관할 보호센터명  1350 non-null   object
 13  대표자       1350 non-null   object
 14  주소        1350 non-null   object
 15  전화번호      1350 non-null   object
dtypes: float64(2), object(14)
memory usage: 168.9+ KB

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1350 entries, 0 to 1349
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   공고번호      1350 non-null   object
 1   동물등록번호    38 non-null     float64
 2   동물종류      1350 non-null   object
 3   품종        1350 non-null   object
 4   털색        0 non-null      float64
 5   성별        1350 non-null   object
 6   중성화 여부    1350 non-null   object
 7   특징        1350 non-null   object
 8   구조일       1350 non-null   object
 9   구조사유      351 non-null    object
 10  구조장소      1350 non-null   object
 11  공고기간      1350 non-null   object
 12  관할 보호센터명  1350 non-null   object
 13  대표자       1350 non-null   object
 14  주소        1350 non-null   object
 15  전화번호      1350 non-null   object
dtypes: float64(2), object(14)
memory usage: 168.9+ KB

In [ ]:
df3.drop(['공고번호','동물등록번호','털색','특징','구조사유','구조장소','대표자'], axis=1, inplace=True)

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1350 entries, 0 to 1349
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   동물종류      1350 non-null   object
 1   품종        1350 non-null   object
 2   성별        1350 non-null   object
 3   중성화 여부    1350 non-null   object
 4   구조일       1350 non-null   object
 5   공고기간      1350 non-null   object
 6   관할 보호센터명  1350 non-null   object
 7   주소        1350 non-null   object
 8   전화번호      1350 non-null   object
dtypes: object(9)
memory usage: 95.1+ KB

In [ ]:
a = df3['동물종류'].value_counts()
print(a)

동물종류
개      874
고양이    454
기타      22
Name: count, dtype: int64

In [ ]:
b = df3['품종'].value_counts()
print(b)

품종
믹스견             732
한국 고양이          396
믹스묘              48
푸들               34
말티즈              24
포메라니안            13
진도견               8
비숑 프리제            7
시츄                7
토끼                6
시바                5
요크셔 테리어           5
라브라도 리트리버         4
염소                4
시베리안 허스키          4
프렌치 불독            3
닭                 3
페르시안              3
스코티시폴드            2
토이 푸들             2
페키니즈              2
골든 리트리버           2
웰시 코기 펨브로크        2
애왼용쥐              2
앵무새               2
코카 스파니엘           2
미니어쳐 핀셔           2
테리어 믹스            1
미니어쳐 슈나우저         1
러시안 블루            1
라이카믹스             1
말티푸               1
풍산견               1
웰시진도믹스            1
집기러기              1
흑염소               1
스핑크스              1
미니어쳐 푸들           1
애완토끼              1
스탠다드 닥스훈트         1
거북이               1
아메리칸불리            1
보더 콜리             1
터키시 앙고라           1
샴                 1
달마시안              1
미니어쳐 닥스훈트         1
먼치킨               1
말라뮤트              1
센트럴 아시안 오브차카      1
핏불테리어             1
왕관앵무              1
비글                1
Name: count, dtype: int64

In [ ]:
df3["품종(상위)"] = df3['품종']

In [ ]:
df3.drop(['품종'], axis=1, inplace=True)

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1350 entries, 0 to 1349
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   동물종류      1350 non-null   object
 1   성별        1350 non-null   object
 2   중성화 여부    1350 non-null   object
 3   구조일       1350 non-null   object
 4   공고기간      1350 non-null   object
 5   관할 보호센터명  1350 non-null   object
 6   주소        1350 non-null   object
 7   전화번호      1350 non-null   object
 8   품종(상위)    1350 non-null   object
dtypes: object(9)
memory usage: 95.1+ KB

In [ ]:
df3['성별'] = df3['성별'].fillna('미상')
df3['중성화 여부'] = df3['중성화 여부'].fillna('미확인')
df3['중성화 여부'] = df3['중성화 여부'].replace({'예':'O','아니오':'X'})

In [ ]:
df3['구조일'] = pd.to_datetime(df3['구조일'], format='%Y-%m-%d')
date_counts = df3['구조일'].value_counts().sort_index()

In [ ]:
df3['관할 보호센터명'] = df3['관할 보호센터명'].fillna('미상')

In [ ]:
df3.drop(['전화번호'], axis=1, inplace=True)

In [ ]:
df3['성별'] = df3['성별'].replace({'암컷':"여", "수컷":"남"})

In [ ]:
df3.to_csv('정제된 반환대상 동물공고_20250516.csv', index=False, encoding='utf-8-sig')
files.download('정제된 반환대상 동물공고_20250516.csv')

In [ ]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   번호      322 non-null    int64
 1   관할구역    322 non-null    object
 2   보호센터명   322 non-null    object
 3   전화번호    322 non-null    object
 4   주소      322 non-null    object
dtypes: int64(1), object(4)
memory usage: 12.7+ KB

In [ ]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5296 entries, 0 to 5295
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   번호      5296 non-null   int64
 1   병원명     5296 non-null   object
 2   전화번호    5051 non-null   object
 3   소재지     5233 non-null   object
 4   인허가번호   5296 non-null   int64
dtypes: int64(2), object(3)
memory usage: 207.0+ KB