In [1]:
import pandas as pd
import re

In [2]:
df = pd.read_excel('입양대상 동물_20250516.xls')
df_hospital = pd.read_excel('동물병원 목록_20250516.xls')
df_shelter = pd.read_excel('동물보호센터 목록_20250516.xls')

## 전처리 함수

In [3]:
def extract_type(x):
    return re.search(r'\[(.*?)\]', x).group(1) if '[' in x else '기타'

def extract_kind(x):
    return re.sub(r'\[.*?\]\s*', '', x)

## 입양대상_동물

In [4]:
df = df[['공고번호', '품종', '성별', '접수일시', '관할기관', '보호센터']]
df.columns = ['announced_num', 'kind', 'sex', 'received_date', 'province', 'shelter']

In [5]:
df['animal_type'] = df['kind'].apply(extract_type)
df['kind'] = df['kind'].apply(extract_kind)

In [6]:
df = df[['received_date', 'animal_type', 'kind', 'sex', 'province', 'shelter']]
df.head()

  received_date animal_type    kind sex   province   shelter
0    2025-05-15         고양이  한국 고양이  암컷  광주광역시 광산구  광주동물보호센터
1    2025-05-15         고양이  한국 고양이  암컷   광주광역시 남구  광주동물보호센터
2    2025-05-15         고양이  한국 고양이  수컷   광주광역시 동구  광주동물보호센터
3    2025-05-15         고양이  한국 고양이  수컷   광주광역시 동구  광주동물보호센터
4    2025-05-15         고양이  한국 고양이  수컷   광주광역시 동구  광주동물보호센터

## 동물 병원 목록

In [7]:
df_hospital = df_hospital[['병원명', '소재지', '인허가번호']]
df_hospital.head()

                      병원명                    소재지               인허가번호
0  (주)에니멀클리닉컨설팅(출장진료전문병원)        경기도 용인시 기흥구 신갈동  563000001020130004
1                 119동물병원      대구광역시 달성군 다사읍 매곡리  348000001020160002
2               21세기 동물병원  전북특별자치도 전주시 덕진구 송천동1가  464100001019990001
3                21세기동물병원            전라남도 목포시 상동  480000001020010001
4                21세기동물병원            경기도 화성시 반송동  553000001020100001

In [8]:
df_hospital.columns = ['hospital_name', 'location', 'id_code']
df_hospital.head()

            hospital_name               location             id_code
0  (주)에니멀클리닉컨설팅(출장진료전문병원)        경기도 용인시 기흥구 신갈동  563000001020130004
1                 119동물병원      대구광역시 달성군 다사읍 매곡리  348000001020160002
2               21세기 동물병원  전북특별자치도 전주시 덕진구 송천동1가  464100001019990001
3                21세기동물병원            전라남도 목포시 상동  480000001020010001
4                21세기동물병원            경기도 화성시 반송동  553000001020100001

## 동물보호센터 목록

In [9]:
df_shelter = df_shelter[['관할구역', '보호센터명']]
df_shelter.head()

        관할구역        보호센터명
0  대구광역시 수성구    (사)대구수의사회
1   경상남도 김해시  (사)동물보호관리협회
2  부산광역시 동래구  (사)동부동물보호협회
3   부산광역시 남구  (사)동부동물보호협회
4  부산광역시 수영구  (사)동부동물보호협회

In [10]:
df_shelter.columns = ['turf', 'center_name']
df_shelter.head()

        turf  center_name
0  대구광역시 수성구    (사)대구수의사회
1   경상남도 김해시  (사)동물보호관리협회
2  부산광역시 동래구  (사)동부동물보호협회
3   부산광역시 남구  (사)동부동물보호협회
4  부산광역시 수영구  (사)동부동물보호협회

In [11]:
df.to_csv('abandoned_animal.csv', index=False, encoding='utf-8-sig')
df_hospital.to_csv('hospital.csv', index=False, encoding='utf-8-sig')
df_shelter.to_csv('shelter.csv', index=False, encoding='utf-8-sig')

In [12]:
df = pd.read_csv('abandoned_animal.csv')
print(df.columns)
print(df.head())

Index(['received_date', 'animal_type', 'kind', 'sex', 'province', 'shelter'], dtype='object')
  received_date animal_type    kind sex   province   shelter
0    2025-05-15         고양이  한국 고양이  암컷  광주광역시 광산구  광주동물보호센터
1    2025-05-15         고양이  한국 고양이  암컷   광주광역시 남구  광주동물보호센터
2    2025-05-15         고양이  한국 고양이  수컷   광주광역시 동구  광주동물보호센터
3    2025-05-15         고양이  한국 고양이  수컷   광주광역시 동구  광주동물보호센터
4    2025-05-15         고양이  한국 고양이  수컷   광주광역시 동구  광주동물보호센터